const { EmbedBuilder } = require('discord.js');

module.exports = {
    name: 'code',
    aliases: ['generate', 'program'],
    description: 'Generate code in various programming languages',
    async execute(message, args) {
        const { client } = message;
        
        if (args.length < 2) {
            await message.reply("Yo fam, I need a language and description! Try: `!code javascript create a function that adds two numbers`");
            return;
        }

        const language = args[0].toLowerCase();
        const description = args.slice(1).join(' ');

        // Show typing indicator
        const typingMessage = await message.reply('🤖 **Zolory is generating code...** Please wait!');

        try {
            const code = await client.zoloryAI.generateCode(language, description);
            
            const embed = new EmbedBuilder()
                .setTitle(`💻 Code Generated - ${language.toUpperCase()}`)
                .setColor('#00ff00')
                .setDescription(`**Description:** ${description}`)
                .addFields(
                    { name: '🔤 Language', value: language.toUpperCase(), inline: true },
                    { name: '👨‍💻 Generated by', value: client.config.botPersonality.name, inline: true },
                    { name: '📅 Generated at', value: new Date().toLocaleString(), inline: true }
                )
                .setFooter({ text: `Requested by ${message.author.tag}` })
                .setTimestamp();

            await typingMessage.edit({ content: null, embeds: [embed] });
            await message.channel.send(code);

        } catch (error) {
            console.error('Error generating code:', error);
            await typingMessage.edit("Yo, my brain's lagging rn! I couldn't generate that code! 😅");
        }
    }
};